FROM maven:latest

ARG POSTGRES_CONNECTION_STRING
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD

ENV POSTGRES_CONNECTION_STRING=$POSTGRES_CONNECTION_STRING
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

WORKDIR .
COPY . .
RUN ["mvn", "install"]

ENTRYPOINT ["java","-jar","./target/ccbrec-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080